#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2017 LasLabs Inc.

from glob import glob
from os.path import basename, join, splitext

from doodbalib import CUSTOM_DIR, FILE_APT_BUILD, SRC_DIR
from doodbalib.installer import INSTALLERS, install, logger

# Build dependencies installed before any others
install("apt", FILE_APT_BUILD)
